CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categoris (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE `categoris` ADD `title` VARCHAR(255) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `categoris` ADD `image` VARCHAR(255) NULL DEFAULT NULL AFTER `title`;
ALTER TABLE `categoris` ADD `description` VARCHAR(255) NULL DEFAULT NULL AFTER `image`;

CREATE TABLE products( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP );
ALTER TABLE `products` ADD `title` VARCHAR(255) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `products` ADD `description` TEXT NULL AFTER `title`;
ALTER TABLE `products` ADD `cat_id` INT NULL AFTER `description`;
ALTER TABLE `products` ADD `maintain` TEXT NULL AFTER `cat_id`;
ALTER TABLE `products` ADD `price` DECIMAL(10,4) NULL AFTER `maintain`;
ALTER TABLE `products` ADD `sale_price` DECIMAL(13,2) NULL DEFAULT '0' AFTER `price`;
ALTER TABLE `products` ADD `image` VARCHAR(255) NULL AFTER `price`;


CREATE TABLE price_size( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP );

ALTER TABLE `price_size` ADD `title` VARCHAR(255) NULL AFTER `id`;
ALTER TABLE `price_size` ADD `active` BOOLEAN NOT NULL DEFAULT TRUE AFTER `title`;

CREATE TABLE product_category( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP )
ALTER TABLE `product_category` ADD `product_id` INT(10) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `product_category` ADD `category_id` INT(10) NULL DEFAULT NULL AFTER `product_id`;

CREATE TABLE product_price_size( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP )
ALTER TABLE `price_size` ADD `product_id` INT(10) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `price_size` ADD `size_id` INT(10) NULL AFTER `product_id`;

CREATE TABLE product_imgs( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP )
ALTER TABLE `product_imgs` ADD `product_id` INT(10) NULL DEFAULT NULL AFTER `id`;
ALTER TABLE `product_imgs` ADD `img` VARCHAR(255) NULL DEFAULT NULL AFTER `product_id`;

